# Semana 6 — Fuentes de datos reales y procesos ETL con Pandas

**Unidad 2:** Adquisición, limpieza y transformación de datos  
**Tema:** Fuentes de datos reales: Kaggle, UCI, datos abiertos y archivos propios. Procesos ETL: extracción, transformación y carga. Lectura y carga de datos con Pandas.  

## Propósito de la clase

En esta clase se introduce el flujo básico de adquisición de datos reales y el proceso ETL: **extracción, transformación y carga**. El estudiante aprenderá a identificar fuentes de datos, cargar archivos con Pandas, documentar la fuente del dataset y guardar una versión preliminar procesada.

## Resultados esperados

1. Reconocer diferentes fuentes de datos reales.
2. Diferenciar datos de Kaggle, UCI, datos abiertos y archivos propios.
3. Cargar archivos CSV, Excel y JSON con `pandas`.
4. Ejecutar un flujo ETL básico.
5. Crear una ficha técnica inicial del dataset.
6. Guardar datos originales en `data/raw` y datos procesados en `data/processed`.

## 1. Concepto general de ETL

## 2. Preparación del entorno

In [1]:
from pathlib import Path
import pandas as pd
import numpy as np
from io import StringIO
import json

# Carpetas de trabajo
Path("data/raw").mkdir(parents=True, exist_ok=True)       # Datos en bruto
Path("data/processed").mkdir(parents=True, exist_ok=True) # Datos procesados y limpios
Path("reports").mkdir(parents=True, exist_ok=True)        # Gráficas y reportes obtenidos

pd.set_option("display.max_columns", 50)

print("Entorno preparado.")

Entorno preparado.

## 3. Fuentes de datos reales

Durante el curso se usarán varias fuentes:

| Fuente | Descripción | Forma de acceso |
|---|---|---|
| [**Kaggle**](https://www.kaggle.com/) | Plataforma con datasets, notebooks y competiciones | Descarga manual o API |
| [**UCI Machine Learning Repository**](https://archive.ics.uci.edu/) | Repositorio clásico de datasets para análisis y modelamiento | URL directa o descarga |
| [**Datos abiertos Colombia**](https://www.datos.gov.co/) | Portales gubernamentales o institucionales | CSV, Excel, JSON o API |
| **Archivos propios** | Datos generados por el estudiante, laboratorio o empresa | Carga local desde Colab o Drive |

## 4. Archivo propio: crear, guardar y cargar un CSV

Primero simularemos un archivo propio con mediciones de equipos mecatrónicos.

In [2]:
datos_propios = {
    "id_equipo": ["E01", "E02", "E03", "E04", "E05"],
    "tipo_equipo": ["motor", "bomba", "ventilador", "motor", "bomba"],
    "voltaje_V": [12.0, 12.2, 11.8, 12.1, 12.0],
    "corriente_A": [1.8, 2.1, 1.5, 2.8, 3.0],
    "temperatura_C": [36.5, 42.0, 35.2, 48.5, 51.0],
}

df_propios = pd.DataFrame(datos_propios)
df_propios.to_csv("data/raw/mediciones_propias.csv", index=False)

df_propios

  id_equipo tipo_equipo  voltaje_V  corriente_A  temperatura_C
0       E01       motor       12.0          1.8           36.5
1       E02       bomba       12.2          2.1           42.0
2       E03  ventilador       11.8          1.5           35.2
3       E04       motor       12.1          2.8           48.5
4       E05       bomba       12.0          3.0           51.0

In [3]:
# Cargamos el dataset capitalbikeshare.csv
df_propios.to_csv("data/raw/mediciones_propias.csv", index=False)

df_propios

  id_equipo tipo_equipo  voltaje_V  corriente_A  temperatura_C
0       E01       motor       12.0          1.8           36.5
1       E02       bomba       12.2          2.1           42.0
2       E03  ventilador       11.8          1.5           35.2
3       E04       motor       12.1          2.8           48.5
4       E05       bomba       12.0          3.0           51.0

In [4]:
# Cargar archivo capitalbikeshare.csv desde data/raw
df_archivo_propio = pd.read_csv("data/raw/mediciones_propias.csv")
df_archivo_propio.head()

  id_equipo tipo_equipo  voltaje_V  corriente_A  temperatura_C
0       E01       motor       12.0          1.8           36.5
1       E02       bomba       12.2          2.1           42.0
2       E03  ventilador       11.8          1.5           35.2
3       E04       motor       12.1          2.8           48.5
4       E05       bomba       12.0          3.0           51.0

## 5. Carga desde UCI Machine Learning Repository

Usaremos el dataset Iris desde una URL pública de UCI.  
Este dataset es pequeño y permite practicar carga directa desde internet.

In [5]:
url_iris = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

columnas_iris = [
    "sepal_length_cm",
    "sepal_width_cm",
    "petal_length_cm",
    "petal_width_cm",
    "species"
]

try:
    df_uci = pd.read_csv(url_iris, header=None, names=columnas_iris)
    df_uci.to_csv("data/raw/iris_uci_original.csv", index=False)
    print("Dataset UCI cargado correctamente.")
    display(df_uci.head())
except Exception as e:
    print("No fue posible cargar el dataset desde la URL.")
    print("Error:", e)
    df_uci = pd.DataFrame()

Dataset UCI cargado correctamente.

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa

## 6. Carga de datos abiertos

Los datos abiertos se pueden descargar desde portales gubernamentales, institucionales o empresariales.  
La forma de trabajo recomendada es:

1. Descargar el archivo en formato CSV, Excel o JSON.
2. Subirlo a Google Colab.
3. Cargarlo con Pandas.
4. Documentar fuente, fecha de descarga, columnas y limitaciones.

La siguiente celda muestra cómo subir un archivo manualmente en Google Colab.

In [7]:
# En Google Colab, puede descomentar estas líneas para subir un archivo manualmente.
from google.colab import files
archivos = files.upload()

# Después de subir el archivo:
df_datos_abiertos = pd.read_csv("data/raw/Registros_de_Vacunación_contra_Fiebre_Aftosa_y_Especies_Asociadas_en_el_Departamento_del_Vichada_20260911.csv")
df_datos_abiertos.head()

Saving Registros_de_Vacunación_contra_Fiebre_Aftosa_y_Especies_Asociadas_en_el_Departamento_del_Vichada_20260911.csv to Registros_de_Vacunación_contra_Fiebre_Aftosa_y_Especies_Asociadas_en_el_Departamento_del_Vichada_20260911.csv

,CODIGO_DANE_DEPARTAMENTO,DEPARTAMENTO,CODIGO_DANE_MUNICIPIO,MUNICIPIO,VEREDA,PREDIO,TENENCIA,RUV,FECHA_RUV,VIGENCIA,CICLO_VACUNACION,LONGITUD,LATITUD,TOTAL_AFTOSA,EQUINOS,PORCINOS,OVINOS,CAPRINOS
0,99,VICHADA,"99,773",CUMARIBO,PUERTO ORIENTE,TABATINGA,PROPIO,"10,266,907",2024 Oct 28 12:00:00 AM,"2,024",Ciclo II - 2024,-71.030911,4.221275,148,0,0,0,0
1,99,VICHADA,"99,773",CUMARIBO,EL TRIUNFO,CATALINA,PROPIO,"10,257,502",2024 Oct 28 12:00:00 AM,"2,024",Ciclo II - 2024,-68.521105,5.106947,105,0,0,0,0
2,99,VICHADA,"99,773",CUMARIBO,PUERTO ORIENTE,EL ORIENTE,PROPIO,"10,331,828",2024 Oct 28 12:00:00 AM,"2,024",Ciclo II - 2024,-71.035516,4.266528,295,0,0,0,0
3,99,VICHADA,"99,773",CUMARIBO,CHAPARRAL BAJO,EL AFRICA,PROPIO,"10,317,298",2024 Oct 28 12:00:00 AM,"2,024",Ciclo II - 2024,-68.823667,4.771738,130,0,0,0,0
4,99,VICHADA,"99,773",CUMARIBO,UVA ALTO,LA GRANJA,PROPIO,"10,351,021",2024 Oct 28 12:00:00 AM,"2,024",Ciclo II - 2024,-70.423858,3.540712,121,10,15,0,0

## 7. Carga desde Kaggle

Para Kaggle existen dos opciones:

### Opción A — API de Kaggle

No requiere cuenta de Kaggle o archivo `kaggle.json`.

### Opción B — Descarga manual

1. Buscar el dataset en Kaggle.
2. Descargar el archivo `.zip`.
3. Subirlo a Colab.
4. Descomprimirlo.
5. Cargar el CSV con Pandas.

In [8]:
# Ejemplo para descargar y descomprimir un dataset directamente la web de Kaggle.
# Descargamos un daytaset de imágenes comprimido.
# Dir: https://www.kaggle.com/datasets/sanikamal/horses-or-humans-dataset
!mkdir ~/.kaggle
!touch ~/.kaggle/kaggle.json

#Los siguientes datos se obtienen del archivo kaggle.json:
api_token = {"username":"","key":""}

import json

with open('/root/.kaggle/kaggle.json', 'w') as file:
  json.dump(api_token, file)

!chmod 600 ~/.kaggle/kaggle.json

# Después del comando '-d' agregar la ruta del dataset (ver la dirección web)
!kaggle datasets download -d sanikamal/horses-or-humans-dataset

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/sanikamal/horses-or-humans-dataset
License(s): other
Downloading horses-or-humans-dataset.zip to /content
100% 307M/307M [00:03<00:00, 85.3MB/s]

In [10]:
# Ejemplo para descargar y descomprimir un dataset directamente la web de Kaggle.
# Descargamos un daytaset de imágenes comprimido.
# Dir: https://www.kaggle.com/code/saife245/football-match-prediction
!mkdir ~/.kaggle
!touch ~/.kaggle/kaggle.json

#Los siguientes datos se obtienen del archivo kaggle.json:
api_token = {"username":"","key":""}

import json

with open('/root/.kaggle/kaggle.json', 'w') as file:
  json.dump(api_token, file)

!chmod 600 ~/.kaggle/kaggle.json

# Después del comando '-d' agregar la ruta del dataset (ver la dirección web)
!kaggle datasets download -d code/saife245/football-match-prediction

mkdir: cannot create directory ‘/root/.kaggle’: File exists
403 Client Error: Forbidden for url: https://api.kaggle.com/v1/datasets.DatasetApiService/GetDatasetMetadata

In [ ]:
# Con éste código descomprimidos el dataset en la carpeta temporal de Colab:
import os
import zipfile

local_zip = '/content/horses-or-humans-dataset.zip'
zip_ref = zipfile.ZipFile(local_zip, 'r')
zip_ref.extractall('/tmp')
zip_ref.close()

In [ ]:
# Ejemplo general para descomprimir un dataset de Kaggle subido manualmente.
# Cambie el nombre del archivo .zip según corresponda.

# import zipfile
# nombre_zip = "dataset.zip"

# with zipfile.ZipFile(nombre_zip, "r") as zip_ref:
#     zip_ref.extractall("data/raw/kaggle_dataset")

# Luego:
# df_kaggle = pd.read_csv("data/raw/kaggle_dataset/archivo.csv")
# df_kaggle.head()

## 8. Lectura de archivos Excel y JSON

Además de CSV, Pandas permite leer Excel y JSON.

In [11]:
# Cargamos el archivo 12_DICIEMBRE_2020.xlsx y el archivo hpcharactersdataraw.json
# Crear archivos de ejemplo
df_propios.to_excel("data/raw/mediciones_propias.xlsx", index=False)
df_propios.to_json("data/raw/mediciones_propias.json", orient="records", indent=4, force_ascii=False)

# Leer Excel
df_excel = pd.read_excel("data/raw/mediciones_propias.xlsx")

# Leer JSON
df_json = pd.read_json("data/raw/mediciones_propias.json")

display(df_excel.head())
display(df_json.head())

  id_equipo tipo_equipo  voltaje_V  corriente_A  temperatura_C
0       E01       motor       12.0          1.8           36.5
1       E02       bomba       12.2          2.1           42.0
2       E03  ventilador       11.8          1.5           35.2
3       E04       motor       12.1          2.8           48.5
4       E05       bomba       12.0          3.0           51.0

  id_equipo tipo_equipo  voltaje_V  corriente_A  temperatura_C
0       E01       motor       12.0          1.8           36.5
1       E02       bomba       12.2          2.1           42.0
2       E03  ventilador       11.8          1.5           35.2
3       E04       motor       12.1          2.8           48.5
4       E05       bomba       12.0          3.0           51.0

In [13]:
# Leer Excel
df_excel = pd.read_excel("data/raw/12_DICIEMBRE_2020.xlsx")

# Leer JSON
df_json = pd.read_json("data/raw/hpcharactersdataraw.json")

display(df_excel.head())
display(df_json.head())

   Unnamed: 0 TESORERIA MUNICIPAL DE MONTERREY    Unnamed: 2  Unnamed: 3
0         NaN             DIRECCION DE EGRESOS           NaN         NaN
1         NaN                              NaN           NaN         NaN
2         NaN             PAGOS DICIEMBRE 2020           NaN         NaN
3         NaN                              NaN           NaN         NaN
4         NaN                         CONCEPTO  TOTAL PAGADO         NaN

,Name,Link,Descr,Gender,Species/Race,Blood,School,Profession
0,Mrs. Abbott,https://www.hp-lexicon.org/character/abbott-fa...,"Mrs. Abbott was the mother of Hannah Abbott, a...",Female,Witch,Muggle-born,Unknown,Unknown
1,Hannah Abbott,https://www.hp-lexicon.org/character/abbott-fa...,Hannah Abbott is a Hufflepuff student in Harry...,Female,Witch,Half-blood,Hogwarts - Hufflepuff,Landlady of the Leaky Cauldron
2,Abel Treetops,https://www.hp-lexicon.org/character/abel-tree...,Abel Treetops was a wizard from Cincinnati who...,Male,Wizard,Unknown,Unknown,Unknown
3,Euan Abercrombie,https://www.hp-lexicon.org/character/abercromb...,Euan Abercrombie was a small boy with prominen...,Male,Wizard,Unknown,Hogwarts - Gryffindor,Unknown
4,Aberforth Dumbledore,https://www.hp-lexicon.org/character/dumbledor...,"Aberforth Dumbledore was a tall, thin, grumpy-...",Male,Wizard,Half-blood,Hogwarts - Student,Barman

## 9. Función para diagnóstico inicial del dataset

Cuando se carga un dataset, conviene aplicar una revisión inicial estándar.

In [14]:
def diagnostico_inicial(df, nombre_dataset="dataset"):
    print(f"Diagnóstico inicial: {nombre_dataset}")
    print("-" * 50)
    print("Dimensiones:", df.shape)
    print("\nColumnas:")
    print(df.columns.tolist())
    print("\nTipos de datos:")
    display(df.dtypes)
    print("\nPrimeras filas:")
    display(df.head())
    print("\nValores faltantes:")
    display(df.isna().sum())
    print("\nEstadísticas descriptivas:")
    display(df.describe(include="all"))

diagnostico_inicial(df_archivo_propio, "df_archivo_propio")

Diagnóstico inicial: df_archivo_propio
--------------------------------------------------
Dimensiones: (5, 5)

Columnas:
['id_equipo', 'tipo_equipo', 'voltaje_V', 'corriente_A', 'temperatura_C']

Tipos de datos:

id_equipo         object
tipo_equipo       object
voltaje_V        float64
corriente_A      float64
temperatura_C    float64
dtype: object

Primeras filas:

  id_equipo tipo_equipo  voltaje_V  corriente_A  temperatura_C
0       E01       motor       12.0          1.8           36.5
1       E02       bomba       12.2          2.1           42.0
2       E03  ventilador       11.8          1.5           35.2
3       E04       motor       12.1          2.8           48.5
4       E05       bomba       12.0          3.0           51.0

Valores faltantes:

id_equipo        0
tipo_equipo      0
voltaje_V        0
corriente_A      0
temperatura_C    0
dtype: int64

Estadísticas descriptivas:

       id_equipo tipo_equipo  voltaje_V  corriente_A  temperatura_C
count          5           5   5.000000     5.000000       5.000000
unique         5           3        NaN          NaN            NaN
top          E01       motor        NaN          NaN            NaN
freq           1           2        NaN          NaN            NaN
mean         NaN         NaN  12.020000     2.240000      42.640000
std          NaN         NaN   0.148324     0.642651       7.030149
min          NaN         NaN  11.800000     1.500000      35.200000
25%          NaN         NaN  12.000000     1.800000      36.500000
50%          NaN         NaN  12.000000     2.100000      42.000000
75%          NaN         NaN  12.100000     2.800000      48.500000
max          NaN         NaN  12.200000     3.000000      51.000000

## 10. Transformación mínima

En un flujo ETL inicial no siempre se hace limpieza profunda.  
La transformación mínima puede incluir:

- Normalizar nombres de columnas.
- Agregar una columna de fuente.
- Calcular una variable simple.
- Seleccionar columnas relevantes.
- Guardar una versión preliminar.

In [15]:
def normalizar_columnas(df):
    df = df.copy()
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
    )
    return df

df_etl = normalizar_columnas(df_archivo_propio)
df_etl["fuente"] = "archivo_propio"
df_etl["potencia_W"] = df_etl["voltaje_v"] * df_etl["corriente_a"]

df_etl

,id_equipo,tipo_equipo,voltaje_v,corriente_a,temperatura_c,fuente,potencia_W
0,E01,motor,12.0,1.8,36.5,archivo_propio,21.60
1,E02,bomba,12.2,2.1,42.0,archivo_propio,25.62
2,E03,ventilador,11.8,1.5,35.2,archivo_propio,17.70
3,E04,motor,12.1,2.8,48.5,archivo_propio,33.88
4,E05,bomba,12.0,3.0,51.0,archivo_propio,36.00

## 11. Carga o guardado del resultado

En este curso, la etapa de carga se entiende como guardar el dataset organizado en la carpeta `data/processed`.

In [16]:
df_etl.to_csv("data/processed/mediciones_propias_etl.csv", index=False)
print("Archivo guardado en data/processed/mediciones_propias_etl.csv")

Archivo guardado en data/processed/mediciones_propias_etl.csv

## 12. Ficha técnica inicial del dataset

Todo dataset debe documentarse.  
La ficha técnica ayuda a entender la procedencia y las condiciones de uso.

In [17]:
ficha_dataset = {
    "nombre_dataset": "Mediciones propias de equipos mecatrónicos",
    "fuente": "Simulación / archivo propio de clase",
    "formato_original": "CSV",
    "fecha_descarga_o_creacion": "2026-09-11",
    "numero_filas": df_archivo_propio.shape[0],
    "numero_columnas": df_archivo_propio.shape[1],
    "columnas_principales": ", ".join(df_archivo_propio.columns),
    "posible_uso": "Explorar variables eléctricas y térmicas de equipos",
    "limitaciones": "Dataset pequeño y simulado para práctica inicial",
}

df_ficha = pd.DataFrame([ficha_dataset])
df_ficha.to_csv("reports/ficha_dataset_mediciones_propias.csv", index=False)

df_ficha

,nombre_dataset,fuente,formato_original,fecha_descarga_o_creacion,numero_filas,numero_columnas,columnas_principales,posible_uso,limitaciones
0,Mediciones propias de equipos mecatrónicos,Simulación / archivo propio de clase,CSV,2026-09-11,5,5,"id_equipo, tipo_equipo, voltaje_V, corriente_A...",Explorar variables eléctricas y térmicas de eq...,Dataset pequeño y simulado para práctica inicial

## 13. Flujo ETL completo en una función

Podemos encapsular el flujo básico en una función.

In [18]:
def etl_archivo_csv(ruta_entrada, ruta_salida, fuente):
    # Extract
    df = pd.read_csv(ruta_entrada)

    # Transform
    df = normalizar_columnas(df)
    df["fuente"] = fuente

    if "voltaje_v" in df.columns and "corriente_a" in df.columns:
        df["potencia_w"] = df["voltaje_v"] * df["corriente_a"]

    # Load
    df.to_csv(ruta_salida, index=False)

    return df

df_resultado = etl_archivo_csv(
    ruta_entrada="data/raw/mediciones_propias.csv",
    ruta_salida="data/processed/mediciones_propias_etl_funcion.csv",
    fuente="archivo_propio"
)

df_resultado

,id_equipo,tipo_equipo,voltaje_v,corriente_a,temperatura_c,fuente,potencia_w
0,E01,motor,12.0,1.8,36.5,archivo_propio,21.60
1,E02,bomba,12.2,2.1,42.0,archivo_propio,25.62
2,E03,ventilador,11.8,1.5,35.2,archivo_propio,17.70
3,E04,motor,12.1,2.8,48.5,archivo_propio,33.88
4,E05,bomba,12.0,3.0,51.0,archivo_propio,36.00

## 14. Observaciones finales

En esta clase se trabajó el flujo:

```text
fuente de datos
→ extracción
→ carga con Pandas
→ diagnóstico inicial
→ transformación mínima
→ guardado en data/processed
→ documentación mediante ficha técnica